### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by A-Rain** [Maluuba/nlg-eval#100]
![nlg-eval](https://user-images.githubusercontent.com/29532760/86425970-1a390d00-bd19-11ea-858e-c988eb8ef276.PNG)
When I'm running computing metrics, I met this problem. How can I solve it?

**Comment by juharris** [comment]
Thanks for trying out our library.
Can you give some more details like what the input the was that caused this?
Is there anything else helpful above this stacktrace? That message "invalid value encountered..." could be related.

**Comment by A-Rain** [comment]
Hi, I found it was my own problem. It turns out that there are some empty sentence in my hypothesis file :(, which cause assertion error. But I also found that Bleu score calculated by NLTK is dfferent from nlg-eval. Could you explain this situation?

**Comment by juharris** [comment]
There are some differences with how we calculate the BLEU score. Maybe #35 is helpful?

**Comment by bricksdont** [comment]
The BLEU implementation in NLTK is not canonical. Currently the most authoritative implementation of BLEU is https://github.com/mjpost/sacreBLEU. nlg-eval should perhaps produce the same scores as sacrebleu, but not NLTK.

**Comment by kracwarlock** [comment]
same issue with NLTK's METEOR implementation https://github.com/nltk/nltk/issues/2365#issuecomment-522385984
