### ISSUE TITLE
Disable Meteor metric

### ISSUE THREAD

**Issue by avinashsai** [Maluuba/nlg-eval#102]
Hi,
Thanks for the amazing library. As a suggestion, I think there should be a choice for users to select which metrics to be computed.
I need to disable computing meteor metric as it is consuming lot of memory.

**Comment by juharris** [comment]
Thanks for the feedback. We do have this option. The README here https://github.com/Maluuba/nlg-eval#usage links to more examples here: https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/tests/test_nlgeval.py
You can use the `metrics_to_omit` option on the `NLGEval` object:
```python
nlg_eval = NLGEval(metrics_to_omit=['METEOR'])
```
