### ISSUE TITLE
Different values for same API

### ISSUE THREAD

**Issue by avinashsai** [Maluuba/nlg-eval#103]
pred_small.txt = [hi , please tell me what i can help you with ?
                            ok . this helpful
                           just give me a few seconds to search through my catalog quickly
                          the length in 2nd image is full
                          the length in 3rd image is full length
                          the similar looking ones are
                          no]

truth.txt = [hi, please tell me, anything i can help you with?
                  okay good!
                  just wait a few seconds while i scan through my catalog
                  the length in 2nd image is full length
                 the length in 3rd image is full length
                 the similar looking ones are
                 yes]

For the above files:
metrics_dict = compute_metrics('pred_small.txt', ['truth.txt'])
Bleu_1: 0.673469
Bleu_2: 0.633147
Bleu_3: 0.585229
Bleu_4: 0.532120
METEOR: 0.438518

However, when excluded meteor:
omit_metrics = ['METEOR', 'CIDEr']
nlgeval = NLGEval(no_skipthoughts=True, no_glove=True, metrics_to_omit = omit_metrics)

metrics_dict = nlgeval.compute_metrics('pred_small.txt', ['truth.txt'])
{'ROUGE_L': 0.0, 'Bleu_4': 5.62341324487423e-09, 'Bleu_3': 9.999999986666689e-10, 'Bleu_2': 3.162277655424966e-11, 'Bleu_1': 9.99999998000001e-16}

I dont understand why the values are different.

**Comment by juharris** [comment]
Thanks for trying nlg-eval.
`NLGEval.compute_metrics` runs directly on those strings and does not attempt to interpret those as files.

**Comment by avinashsai** [comment]
@juharris Thanks for your feedback. However, I have tried with all possible API's but was unable to reproduce results. Can you please try with the example provided?

**Comment by juharris** [comment]
You will have to load those files into lists.  The README links to some examples here: https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/tests/test_nlgeval.py

Also notice that the order of the parameters has been flipped between those two methods. Sorry for the confusion. We wanted to change it but we don't want to make breaking changes. We assume people will usually just use one of the two methods.

**Comment by avinashsai** [comment]
I have loaded them into lists and used the same API given in README. But those values are not at all equal. I have tried multiple times but could not reproduce. If you can run with the above values, please let me know if you can reproduce the results.

**Comment by juharris** [comment]
Ah right, this is sort of intended. See #84  for details.

**Comment by juharris** [comment]
Sorry nevermind, that was for `compute_individual_metrics`

**Comment by avinashsai** [comment]
@juharris any feedback on this?
