### ISSUE TITLE
Different values for same API

### ISSUE THREAD

**Issue by avinashsai** [Maluuba/nlg-eval#104]
The same issue was raised in #103. However, it was closed without any result. Hence. I am raising this issue again.

pred_small.txt = [hi , please tell me what i can help you with ?
ok . this helpful
just give me a few seconds to search through my catalog quickly
the length in 2nd image is full
the length in 3rd image is full length
the similar looking ones are
no]

truth.txt = [hi, please tell me, anything i can help you with?
okay good!
just wait a few seconds while i scan through my catalog
the length in 2nd image is full length
the length in 3rd image is full length
the similar looking ones are
yes]

For the above files:
metrics_dict = compute_metrics('pred_small.txt', ['truth.txt'])
Bleu_1: 0.673469
Bleu_2: 0.633147
Bleu_3: 0.585229
Bleu_4: 0.532120
METEOR: 0.438518

However, when excluded meteor:
omit_metrics = ['METEOR', 'CIDEr']
nlgeval = NLGEval(no_skipthoughts=True, no_glove=True, metrics_to_omit = omit_metrics)

metrics_dict = nlgeval.compute_metrics('pred_small.txt', ['truth.txt'])
{'ROUGE_L': 0.0, 'Bleu_4': 5.62341324487423e-09, 'Bleu_3': 9.999999986666689e-10, 'Bleu_2': 3.162277655424966e-11, 'Bleu_1': 9.99999998000001e-16}

I dont understand why the values are different.

**Comment by juharris** [comment]
Thanks for trying nlg-eval.
`NLGEval.compute_metrics` runs directly on those strings and does not attempt to interpret those as files. So the example above is running directly on the strings: `'pred_small.txt', ['truth.txt']` and NOT opening the files.

**Comment by avinashsai** [comment]
@juharris  i have tried them as lists only. i loaded files into lists and tried all the API's. The results are not the same as the 1st one. Please try them once as lists and let me know if you can reproduce those.

The values should exactly match these:
Bleu_1: 0.673469
Bleu_2: 0.633147
Bleu_3: 0.585229
Bleu_4: 0.532120
METEOR: 0.438518

**Comment by juharris** [comment]
Please share your code. Did you see my comment here: https://github.com/Maluuba/nlg-eval/issues/103#issuecomment-680977511 ?
> Also notice that the order of the parameters has been flipped between those two methods. Sorry for the confusion. We wanted to change it but we don't want to make breaking changes. We assume people will usually just use one of the two methods.

**Comment by avinashsai** [comment]
@juharris I am extremely sorry. All the while I was loading different file. I identified it now. Sorry for all the inconvenience caused.
