### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/nlgeval/rc.json'

### ISSUE THREAD

**Issue by jack-wxm** [Maluuba/nlg-eval#112]
why can not find rc.json?

**Comment by juharris** [comment]
Maybe it got deleted? Try running `nlg-eval --setup` again.

**Comment by jack-wxm** [comment]
> Maybe it got deleted? Try running `nlg-eval --setup` again.

show this mistake: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /moses-smt/mosesdecoder/b199e654df2a26ea58f234cbb642e89d9c1f269d/scripts/generic/multi-bleu.perl (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2fab699cc0>: Failed to establish a new connection: [Errno 111] Connection refused',))
it have downloaded glove.txt and other files

**Comment by temporaer** [comment]
maybethe error is transient, I cannot reproduce on my end. Please make sure you able to access https://raw.githubusercontent.com/moses-smt/mosesdecoder/b199e654df2a26ea58f234cbb642e89d9c1f269d/scripts/generic/multi-bleu.perl in the browser?
