### ISSUE TITLE
Unable to run `compute_metrics` with single reference per hypothesis

### ISSUE THREAD

**Issue by aleSuglia** [Maluuba/nlg-eval#114]
Hello,

In my use case, I would like to use the Object-oriented API that computes the metrics for multiple examples. In my use case, I have a single reference per hypothesis. 

```
from nlgeval import NLGEval


hyp = [
    "This is an hypothesis",
    "Another hypothesis"
]

ref1 = [
    "A reference"
]


ref2 = [
    "another one"
]

nlge = NLGEval(no_skipthoughts=True)

hyp_list = hyp
ref_list = [ref1, ref2]
res = nlge.compute_metrics(ref_list, hyp_list)
```

This code gives the following error:

```
Traceback (most recent call last):
  File "/Users/asuglia/workspace/hero/testeval.py", line 22, in <module>
    res = nlge.compute_metrics(ref_list, hyp_list)
  File "/Users/asuglia/anaconda3/envs/devel/lib/python3.8/site-packages/nlgeval/__init__.py", line 292, in compute_metrics
    assert len(refs) == len(hyps)
AssertionError
```

I'm using Python3.8 with the latest version of this library. Thanks for your help!

**Comment by juharris** [comment]
Thanks for trying out nlg-eval!

Each inner list in `ref_list` needs to have the same length as `hyp`: https://github.com/Maluuba/nlg-eval#object-oriented-api-for-repeated-calls-in-a-script---multiple-examples

You can see examples in here: https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/tests/test_nlgeval.py

**Comment by aleSuglia** [comment]
Sorry, but I'm not following. In my setup, I have a *single* reference for each hypothesis. Why can't I use it the way I coded it? My intuition is the following: for every hypothesis, I have a list of references whose size is 1 because I have a single reference. Am I wrong?

**Comment by juharris** [comment]
Did the examples help? They should explain everything.

Maybe what you want is:
`ref_list = [[ "A reference",  "another one" ]]` ?

**Comment by aleSuglia** [comment]
For instance, from your example how can you tell that the first reference is for the first hypothesis and the second one is for the second? The way I would have implemented the procedure is by computing BLEU (for instance) between `hypothesis_list[i]` and `reference_lists[i]` where `reference_list[i]` is a list of references for the hypothesis `i`. Am I missing something here?

**Comment by juharris** [comment]
The order of the elements in each inner reference list matches the order in the hypothesis. The text in each string in the example should clarify that: https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/tests/test_nlgeval.py#L34

**Comment by aleSuglia** [comment]
Gotcha. May I ask why is that?

**Comment by juharris** [comment]
@kracwarlock or @temporaer  might be able to clarify exactly why the input is set up that way but I believe it's consistent with other libraries.

**Comment by kracwarlock** [comment]
yes the coco-caption library this project builds upon used the same structure and it was used quite a lot at the time so we went with it for ease of use for existing users.

**Comment by aleSuglia** [comment]
I see. Thanks for clarifying that. I found it a bit counterintuitive compared to the simplicity of Huggingface metrics. Anyway, we can close the issue. Thanks again for your support!
