### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by 18166035475** [Maluuba/nlg-eval#122]
I also meet this problem. I have successfully run it once, but when I run it again, this error appears.
![image](https://user-images.githubusercontent.com/36977255/125909891-fa4985fa-b46f-4bef-a65c-2af19fd0db35.png)
![image](https://user-images.githubusercontent.com/36977255/125909975-839e51d2-a080-4081-822c-e30c8de26736.png)
![image](https://user-images.githubusercontent.com/36977255/125910033-b9494116-8d1c-4bee-bc90-48f021ac6220.png)

**Comment by juharris** [comment]
Thanks for using nlg-eval!
utable.npy is too small. See https://github.com/Maluuba/nlg-eval#validate-the-setup-optional

**Comment by juharris** [comment]
Solution: Delete utable.npy and run `nlg-eval --setup` again.

**Comment by 18166035475** [comment]
thank you
