### ISSUE TITLE
TypeError: compute_individual_metrics() missing 1 required positional argument: 'hyp'

### ISSUE THREAD

**Issue by Dyer233** [Maluuba/nlg-eval#138]
![2e0b8ee2dce5ab316ea5efd1446bdbe](https://user-images.githubusercontent.com/106246170/188448886-041676cb-3bc2-4025-a858-5e8e001b2f3a.jpg)

Hello, when calling the evaluation calculation, I encountered the above problem. How can I solve it?

**Comment by juharris** [comment]
Pass 2 parameters, not a tuple: `compute_individual_metrics(references, hypothesis)`

**Comment by Dyer233** [comment]
Thank you for your reply
