### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Dyer233** [Maluuba/nlg-eval#139]
![0d7e3d6ddd2edb2442ccbf60be5e097](https://user-images.githubusercontent.com/106246170/188537476-d4c61d65-65af-481d-91d5-aedb1b6e5696.jpg)
Hello, this kind of problem appeared when calculating the evaluation index. It seems to be a format problem, but I didn't find the problem

**Comment by juharris** [comment]
Your inputs are the wrong format. See the examples in https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/tests/test_nlgeval.py.
