### ISSUE TITLE
METEOR for languages other than English

### ISSUE THREAD

**Issue by soloice** [Maluuba/nlg-eval#14]
If I provide a paraphrase file for some target language other than English, is it possible to run METEOR evaluation on my new target language with `nlg-eval`?
If so, how? By simply replacing the data in METEOR submodule?
Thank you!

**Comment by soloice** [comment]
lol~
Thanks for your reply, and I'm working on rewrite METEOR in Python!

**Comment by temporaer** [comment]
keep us updated, happy to add this as a backend and drop the java dependency!

**Comment by soloice** [comment]
Now I've finished a version of Meteor Universal in Python 2.7 (I hope it also works with Python 3, but I haven't tested it yet), see[here](https://github.com/soloice/MultiAlign/blob/master/src/evaluation/meteor.py).

Currently it only supports Chinese, because I haven't added English Stemmer or WordNet synset stuffs.

I'm working on my master's thesis these days, so I'm kind of rush. After finishing my thesis (hopefully in a month or two), I'll polish my code, refine the comments and add more language supports.

Hope my work can help other people in the NLP community!
