### ISSUE TITLE
what numpy version should i use to run？

### ISSUE THREAD

**Issue by virt9** [Maluuba/nlg-eval#157]
thk for your contribution !  my primary numpy version is 1.26.4,  when using nlg-eval ,it throws" AttributeError: module 'numpy' has no attribute 'bool'."
after i change the numpy version to 1.23.2, it throws another error:AttributeError: module 'numpy.distutils.__config__' has no attribute 'blas_opt_info', and to solve this error i need a new version numpy ,but using new version will throw the first error,  i dont know how to solve

**Comment by temporaer** [comment]
Can you provide a full stack trace for the .bool problem please?

**Comment by virt9** [comment]
> Can you provide a full stack trace for the .bool problem please?

thank u for your response ,i  have solved the problem, and i found that to use the package ,the numpy version should be 1.17 or lower,  that's becouse the version of Cython and theano doesn't fit the new numpy  ,  i don't know except change the numpy version what else can solve this.
