### ISSUE TITLE
bug at setup.sh 

### ISSUE THREAD

**Issue by talrose01** [Maluuba/nlg-eval#16]
hey 
i got an error:

"PYTHONPATH=`pwd` python nlgeval/word2vec/generate_w2v_files.py
'PYTHONPATH' is not recognized as an internal or external command,
operable program or batch file."

at the line:
**PYTHONPATH=`pwd` python2.7 nlgeval/word2vec/generate_w2v_files.py**

i tryed instead:
**python nlgeval/word2vec/generate_w2v_files.py**

and got a different error:
Traceback (most recent call last):
  File "nlgeval/word2vec/generate_w2v_files.py", line 3, in <module>
    from gensim.models import Word2Vec
  File "C:\Python27\lib\site-packages\gensim\__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "C:\Python27\lib\site-packages\gensim\parsing\__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "C:\Python27\lib\site-packages\gensim\parsing\preprocessing.py", line 40, in <module>
    from gensim import utils
  File "C:\Python27\lib\site-packages\gensim\utils.py", line 37, in <module>
    import numpy as np
  File "C:\Python27\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Python27\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Python27\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Python27\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Python27\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: %1 is not a valid Win32 application.

**Comment by talrose01** [comment]
all this bug is about the spicy installation so i will try to remove all the installations and start them again.
there is a special order to install all the python requirments?
thanks

**Comment by kracwarlock** [comment]
Try updating your pip installation as pip handles the order of installation automatically (https://github.com/pypa/pip/pull/2616).

**Comment by juharris** [comment]
@talrose01 I recommend installing Python using [Anaconda/Conda](https://conda.io/docs/user-guide/install/windows.html). Then you can do `conda install scipy`.

**Comment by talrose01** [comment]
i try to install all package by conda.
but when i trying to install theano 0.8.1 i got an error:


**PackagesNotFoundError: The following packages are not available from current channels:

  - theano==0.8.0

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org**



can i import a newer version of theano for this repo? what should i do?
thanks

**Comment by talrose01** [comment]
should i use the conda prompt to run all the command of the repo?

**Comment by juharris** [comment]
It's not always recommended to use Conda to install a package. For example, it might be best to install Theano with pip in your Conda environment.

You can use the Conda prompt to run commands but it is not a Linux like prompt on Windows so you might have to _translate_ commands you see to run on Windows.

**Comment by kracwarlock** [comment]
This issue has been closed due to inactivity. You may reopen this issue if it has been closed in error.
