### ISSUE TITLE
Type of BLEU

### ISSUE THREAD

**Issue by shubhamagarwal92** [Maluuba/nlg-eval#35]
Hi,
Thanks for providing the code. 
I want to confirm if the BLEU-4 score is sentence level BLEU or corpus level BLEU?  
Thanks again.

**Comment by kracwarlock** [comment]
The code computes corpus level BLEU everywhere.

Note: There is a function called `compute_individual_metrics` which runs on individual sentences in which special case the corpus can reduce to a single sentence. However, the computation is still according to corpus level BLEU.

**Comment by shubhamagarwal92** [comment]
Thanks for your prompt reply :) 

Nice to see how you maintain this repo. 0 issues. So closing this as well. 👍
