### ISSUE TITLE
Sequence is shorter then the required number of steps

### ISSUE THREAD

**Issue by kaeflint** [Maluuba/nlg-eval#44]

**Comment by kaeflint** [comment]
Running 
`from nlgeval import NLGEval
nlgeval = NLGEval()
metrics_dict = nlgeval.compute_individual_metrics('The man and woman are on a vacation', 'The couple were on honeymoon.')
`
gave the ValueError: ('Sequence is shorter then the required number of steps : (n_steps, seq, seq.shape):', 1, array([], shape=(0, 1, 1), dtype=float32), (0, 1, 1))

**Comment by juharris** [comment]
Thanks for trying out our repo!
The first parameter (`ref`) should be a list like this:
```python
from nlgeval import NLGEval
nlgeval = NLGEval()
metrics_dict = nlgeval.compute_individual_metrics(["The man and woman are on a vacation"], "The couple were on honeymoon.")
```

You can see some examples here: https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/tests/test_nlgeval.py

**Comment by kaeflint** [comment]
Thanks. working well now but I realized  the ROUGE  scores are different from what I obtained from using the official scripts

**Comment by juharris** [comment]
Thanks for the feedback. Would you open a new issue for that with examples?

**Comment by kracwarlock** [comment]
Our overlap-based metric implementations are derived from https://github.com/tylin/coco-caption. The `ROUGE` metric variant they implement is called `ROUGE_L`. Are you talking about the `ROUGE_L` metric or some other variant of it. If `ROUGE_L` doesn't match the official eval scripts then it would be great if you can open an issue for this.
