### ISSUE TITLE
METEOR source code: 'module' object has no attribute 'unregister'

### ISSUE THREAD

**Issue by Crista23** [Maluuba/nlg-eval#49]
If I try to use the METEOR source code as is, the script crashes on the line below:
https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/pycocoevalcap/meteor/meteor.py#L50

if atexit is not None and atexit.unregister is not None:
AttributeError: 'module' object has no attribute 'unregister'

How can I fix this error? Thank you!

**Comment by juharris** [comment]
Seems like an older version of Python.
Would you run `python --version`?
I recommend using at least Python 3.6 since that's what we mainly test with.  Python 2.7 will also work.

**Comment by Crista23** [comment]
Thanks for your prompt response. I am using Python 2.7:

python --version
Python 2.7.13 :: Anaconda 4.3.1 (64-bit)

**Comment by juharris** [comment]
Oh sorry actually it's because of Python 2.7. I see it in our build [here](https://travis-ci.org/Maluuba/nlg-eval/jobs/438140371).
**This shouldn't cause problems (unless you manually call `close()`.**
If you don't want to see the error then you can upgrade to Python 3.6.
