### ISSUE TITLE
ModuleNotFoundError: No module named 'nlgeval.word2vec.glove2word2vec'

### ISSUE THREAD

**Issue by louismartin** [Maluuba/nlg-eval#50]
There's an error when running `nlg-eval --setup`
```
  File "/private/home/louismartin/miniconda3/lib/python3.6/site-packages/nlgeval/word2vec/generate_w2v_files.py", line 11, in <module>
    from nlgeval.word2vec.glove2word2vec import glove2word2vec
ModuleNotFoundError: No module named 'nlgeval.word2vec.glove2word2vec'
```

Culprit line:
https://github.com/Maluuba/nlg-eval/blob/329dd5b659ba33415616d2d571a07fa1d3073841/nlgeval/word2vec/generate_w2v_files.py#L11

**Comment by juharris** [comment]
What folder are you running the steps from?

**Comment by louismartin** [comment]
I just noticed that the file is ignored by .gitignore:
https://github.com/Maluuba/nlg-eval/blob/580523c4d318720429dedf343be3fd95a3c6dfb2/.gitignore#L21

**Comment by juharris** [comment]
That's right. The setup steps download it: https://github.com/Maluuba/nlg-eval/blob/329dd5b659ba33415616d2d571a07fa1d3073841/bin/nlg-eval#L68-L82

**Comment by juharris** [comment]
Yeah sorry.
We do have this as a goal of ours but it was a little tricky to get done in a nice way with all the files that are required to download. The main issue was that pip was swallowing a lot of the output and not allowing us to convey progress downloading those files which can take awhile.

Unfortunately, for now you do have to script cloning it and running the setup steps (that's what I currently do).

**Comment by juharris** [comment]
Actually! Maybe you can get this working with the `subdirectory` parameter in the repo URL: https://pip.readthedocs.io/en/stable/reference/pip_install/#vcs-support
then cd to that folder and run `nlg-eval --setup`.

**Comment by louismartin** [comment]
Another intermediary solution would be to still install like this `pip install git+https://github.com/Maluuba/nlg-eval.git` but be able to run nlg-eval --setup from any directory (and therefore resolve the nlg-eval installation path instead of using relative paths in the `nlg-eval` script).
This way I can use simple metrics by installing without running `nlg-eval --setup` and when needed, run the setup command to download the additional large files from my python script programmatically (I hope my explanation is clear).

**Comment by juharris** [comment]
That's a good idea.

**Comment by JustinLin610** [comment]
So I met this problem too. I did not quite understand the mentioned solutions. Can I tackle this by cd into the nlg-eval folder and run nlg-eval --setup?

**Comment by juharris** [comment]
You should be able to pip install from a URL now. Check out the setup steps here: https://github.com/Maluuba/nlg-eval#setup
