### ISSUE TITLE
nlg-eval command not found

### ISSUE THREAD

**Issue by achu93** [Maluuba/nlg-eval#61]
I am running the code on a windows machine. I have executed the "pip install -e ." and all packages have been successfully installed. However when I run the next step, "nlg-eval --setup" it throws an error command not found. 

![image](https://user-images.githubusercontent.com/23385897/56009247-c6e63380-5cfc-11e9-8f70-5387b6ea00e4.png)

**Comment by juharris** [comment]
This could be worth looking into but I think people usually use Git Bash when running on Windows. Do you have Git Bash?

**Comment by juharris** [comment]
The easiest way to get around this on Windows CMD is to run:
`python bin\nlg-eval --setup`

**Comment by Krak91** [comment]
Hello,
I was having the same issues. I'm also using windows and pycharm and it seems that the script is located under <project folder>/venv/Scripts/
In my case, **python venv/Scripts/nlg-eval --setup** did the trick.

**Comment by eltonsilvamtm** [comment]
Any other solution for this issue? I tried all the commands posted above but had no success. Really appreciate any help on that.

**Comment by juharris** [comment]
@eltonsilvamtm can you share the errors you got?

**Comment by lethaq** [comment]
Following this, unfortunately I am having issues as well on my Mac M1, tried first to run the command for multithreading, then the command: pip install git+https://github.com/Maluuba/nlg-eval.git@master however I the error I get is related to gensim, tried to uninstall it and run it the setup commands again but with no luck. Any help is highly appreciated!

**Comment by smfsamir** [comment]
@lethaq (and anyone else who runs into the gensim error), I fixed it by forking the project and updating the `requirements.txt` file to use an updated version of `gensim`. In my case, this was `gensim=4.3.1`. I was then able to install `nlg-eval` without issue.
