### ISSUE TITLE
call meteor 

### ISSUE THREAD

**Issue by joseph12346** [Maluuba/nlg-eval#64]
Hi, I want to calculate meteor.

windows 10
java 1.8.0_17
python 3.6.4

code like this:
```python
from __future__ import unicode_literals
import os
import nlgeval

root_dir = os.path.join(os.path.dirname(__file__))
hypothesis = os.path.join(root_dir, 'examples/hyp.txt')
references = os.path.join(root_dir, 'examples/ref1.txt'), os.path.join(root_dir, 'examples/ref2.txt')
scores = nlgeval.compute_metrics(hypothesis, references)
```

  File "C:\Users\214A\Desktop\nlg-eval-master\nlgeval\pycocoevalcap\meteor\meteor.py", line 68, in compute_score
    scores.append(float(dec(self.meteor_p.stdout.readline().strip())))
ValueError: could not convert string to float:

Thanks!

**Comment by joseph12346** [comment]
Thanks your advice!

It print this 
Error handling value: b''
Decoded value:

**Comment by juharris** [comment]
I can't find a nice way to work in a fix and I can't replicate the issues that people get with Meteor.
For now can you add do this:
```python
v = self.meteor_p.stdout.readline()
try:
    scores.append(float(dec(v.strip())))
except:
    sys.stderr.write("Error handling value: {}\n".format(v))
    sys.stderr.write("Decoded value: {}\n".format(dec(v.strip())))
    sys.stderr.write("eval_line: {}\n".format(eval_line))
    raise
```

and if the `eval_line` isn't helpful then also add:
```python
sys.stderr.write("Error from Meteor:\n{}".format(self.meteor_p.stderr.read()))
```
before `raise`.  That line is dangerous because it will hang if there is no stderr from Meteor. So if you find that after adding that line your program never ends, then stop you program and remove it.

**Comment by joseph12346** [comment]
Thanks for your help !!

Error handling value: b'Could not reserve enough space for 2097152KB object heap\n'
Decoded value: Could not reserve enough space for 2097152KB object heap
eval_line: EVAL ||| Error occurred during initialization of VM

**Comment by juharris** [comment]
Ah that's very helpful. It seems like you don't have much memory on your machine?
You can changing that '-Xmx2G' to something lower like '-Xmx1G' in meteor.py.

**Comment by joseph12346** [comment]
It works now !
Thank you!
You've been a lifesaver.

**Comment by juharris** [comment]
Thanks for the feedback. I'll look into adding a warning to help others in the future.
