### ISSUE TITLE
How to find the metrices when two files are exactly same?

### ISSUE THREAD

**Issue by Radhikadua123** [Maluuba/nlg-eval#66]
Hi, 

When I use these lines of code and my two files contain exact same sentences then it produces an assertion error. Why this code is not applicable for two files which are exactly same ?

from nlgeval import compute_metrics
metrics_dict = compute_metrics(hypothesis='nlg-eval/examples/hyp.txt',
                               references=['nlg-eval/examples/ref1.txt'])

Thanks in advance!

**Comment by juharris** [comment]
It should be fine with files that are the same.
What's the error that you got?

I did this which should be equivalent and it was fine:
```bash
$ nlg-eval --hypothesis=examples/hyp.txt --references=examples/hyp.txt
...
Bleu_1: 1.000000
Bleu_2: 1.000000
Bleu_3: 1.000000
Bleu_4: 1.000000
METEOR: 1.000000
ROUGE_L: 1.000000
CIDEr: 10.000000
SkipThoughtsCosineSimilairty: 1.000000
EmbeddingAverageCosineSimilairty: 1.000000
VectorExtremaCosineSimilarity: 1.000000
GreedyMatchingScore: 1.000000
```

**Comment by Radhikadua123** [comment]
Hi,
It worked absolutely fine. Actually my two files seemed to be similar but in one of the file there was an extra newline because of which it produced an assertion error. 
Thanks
