### ISSUE TITLE
Technique to obtain sentence embeddings

### ISSUE THREAD

**Issue by Radhikadua123** [Maluuba/nlg-eval#72]
Hi,
For embedding based metrics, how are the embeddings corresponding to the sentences obtained? 
Thanks in advance!

**Comment by temporaer** [comment]
Do you mean for [word2vec](https://github.com/Maluuba/nlg-eval/blob/12829a2682861d130cfbbeb5d49286538e681e40/nlgeval/word2vec/evaluate.py#L55-L66)?

**Comment by Radhikadua123** [comment]
Yes, I just wanted to know the name of the technique used to obtain the sentence embedding ( as in glove, BERT)

**Comment by kracwarlock** [comment]
We currently use glove
https://github.com/Maluuba/nlg-eval/blob/fe6a9c026e6e13b5b9b8a2a940e59d496b67391a/nlgeval/word2vec/evaluate.py#L18
