### ISSUE TITLE
無法執行

### ISSUE THREAD

**Issue by s00741907** [Maluuba/nlg-eval#85]
我直接下載github的整個code，
想在win10用Anaconda3的Powershell想嘗試NLG，

以下是我run的過程：
```conda create -n nlgeval python=3.7```
```conda activate nlgeval```啟用。

```pip install .```
把nlg-eval-master內的setup.py執行安裝，
然後我再cd到bin資料夾輸入
```python bin\nlg-eval --setup```

接下來我要test
```nlg-eval --hypothesis=examples/hyp.txt --references=examples/ref1.txt --references=examples/ref2.txt```
卻跳出「'nlg-eval' 程式無法執行: 沒有任何應用程式與此操作的指定檔案有關聯。」
請問我在什麼地方沒有做成功呢？

![1015](https://user-images.githubusercontent.com/37057902/66825297-9bc6f000-ef7c-11e9-981f-ca8f2cc3a5ee.png)

**Comment by juharris** [comment]
Thanks for trying nlg-eval!
It could be that Java was not installed. You can check by running `java -h`.

**Comment by juharris** [comment]
Oh actually I think this is because nlg-eval does not get added to the path on Windows.
You can try running it as (from the root folder - that's the folder that contains the examples folder):
`python bin\nlg-eval --hypothesis=examples/hyp.txt --references=examples/ref1.txt --references=examples/ref2.txt`

**Comment by s00741907** [comment]
Thanks for your response.
I have installed Java, the version is 1.8.0_221.
I retry instruction from root folder that it cannot running too.

![1016](https://user-images.githubusercontent.com/37057902/66881650-1f72f200-effa-11e9-8280-45fc7a15aaa7.png)

**Comment by juharris** [comment]
From that folder try running the command as: `python bin\nlg-eval ...` like I gave in the example.

**Comment by s00741907** [comment]
Thanks for your help, I successfully executed it.
![1017](https://user-images.githubusercontent.com/37057902/66974047-79dc8300-f0cc-11e9-96a4-a9879da7f325.png)
