### ISSUE TITLE
CIDEr always giving 0

### ISSUE THREAD

**Issue by Shikib** [Maluuba/nlg-eval#86]
Might be something wrong in my setup. I tried running the following:

` nlgeval.compute_individual_metrics(ref=["the cat in the hat came to town"], hyp="the cat in the hat came to town")`

And got this result:

`{'Bleu_1': 0.9999999997500004, 'Bleu_2': 0.9999999997410718, 'Bleu_3': 0.9999999997301591, 'Bleu_4': 0.9999999997163694, 'METEOR': 1.0, 'ROUGE_L': 1.0, 'CIDEr': 0.0, 'SkipThoughtCS': 1.0, 'EmbeddingAverageCosineSimilairty': 1.0, 'VectorExtremaCosineSimilarity': 1.0, 'GreedyMatchingScore': 1.0}`

Note that CIDEr is 0.

**Comment by juharris** [comment]
Thanks for trying nlg-eval! See https://github.com/Maluuba/nlg-eval/blob/master/README.md#important-note to find out why this is happening.
