### ISSUE TITLE
Typo in "EmbeddingAverageCosineSimilairty"?

### ISSUE THREAD

**Issue by ddehun** [Maluuba/nlg-eval#87]
I think that some of the docs or codes denote "EmbeddingAverageCosineSimilarity" as "EmbeddingAverageCosine**Similairty**". Be careful when using string matching for metric name.

**Comment by juharris** [comment]
omg thanks for pointing that out! I'll add "EmbeddingAverageCosineSimilairty" as a key and keep the old one for backwards compatibility.
