### ISSUE TITLE
evaluation result different with coco-eval and input sensitivity

### ISSUE THREAD

**Issue by soloist97** [Maluuba/nlg-eval#93]
Thanks for your great contribution:)

I evaluated the same hypothesis and references with your code (nlg-eval) and [coco-eval](https://github.com/tylin/coco-caption), but I got different results.

The toy samples I used are listed here:
* Hypothesis 
```json
[
    {"image_id": 404464, "caption": "people are skating in the ice skating rink on the skateboard"},
    {"image_id": 380932, "caption": "group of people are on the side of a snowy field"}, 
    {"image_id": 565778, "caption": "train traveling down a train station"}
]
```
* References
 ```json
[
    {"image_id": 404464, "id": 354054, "caption": " Persons skating in the ice skating rink on the skateboard."},
    {"image_id": 404464, "id": 356931, "caption": "A snowboard sliding very gently across the snow in an enclosure."},
    {"image_id": 404464, "id": 357279, "caption": "A person on a snowboard getting ready for competition."},
    {"image_id": 404464, "id": 358707, "caption": "Man on snowboard riding under metal roofed enclosed area."},
    {"image_id": 404464, "id": 360501, "caption": "A snowboarder practicing his moves at a snow facility."},
    {"image_id": 380932, "id": 85993, "caption": "There are mountains in the background and a lake in the middle."},
    {"image_id": 380932, "id": 92287, "caption": "a red fire hydrant in a field covered in snow"},
    {"image_id": 380932, "id": 97300, "caption": "A fire hydrant in front of a snow covered field, a lake and mountain backdrop."},
    {"image_id": 380932, "id": 98464, "caption": "A hydran in a snow covered field overlooking a lake."},
    {"image_id": 380932, "id": 116026, "caption": "An expanse of snow in the middle of dry plants"},
    {"image_id": 565778, "id": 94048, "caption": "A train going back to its coarse filled with people."},
    {"image_id": 565778, "id": 96433, "caption": "A blue commuter train traveling towards a train tunnel."},
    {"image_id": 565778, "id": 100624, "caption": "Blue train car sitting on a train track near tunnel."}, 
    {"image_id": 565778, "id": 101917, "caption": "A train with people inside is about to go into a tunnel."},
    {"image_id": 565778, "id": 105721, "caption": "A blue train on some train tracks about to go under a bridge"}
]
```

* Results evaluated by coco-caption:

> CIDEr: 1.053
Bleu_4: 0.387
Bleu_3: 0.425
Bleu_2: 0.509
Bleu_1: 0.632
ROUGE_L: 0.556
METEOR: 0.275
SPICE: 0.130

* Results evaluated by nlg-eval:
> Bleu_1: 0.598540
Bleu_2: 0.472135
Bleu_3: 0.383955
Bleu_4: 0.343170
METEOR: 0.267612
ROUGE_L: 0.523820
CIDEr: 0.925046
SkipThoughtsCosineSimilarity: 0.423680
EmbeddingAverageCosineSimilarity: 0.919585
EmbeddingAverageCosineSimilairty: 0.919585
VectorExtremaCosineSimilarity: 0.674633
GreedyMatchingScore: 0.75222

**How can I explain and solve this?**

BTW, I also do tests about case sensitivity and marks (eg. '.'). I found that coco-eval is not sensitive to case and marks, but nlg-eval is sensitive to case and marks.

For example, after changing the first letter from lower case to upper case, results changed (only modified Hypothesis):
> Bleu_1: 0.565288
Bleu_2: 0.435287
Bleu_3: 0.363708
Bleu_4: 0.329506
METEOR: 0.267612
ROUGE_L: 0.480923
CIDEr: 0.838808
SkipThoughtsCosineSimilarity: 0.421886
EmbeddingAverageCosineSimilarity: 0.916779
EmbeddingAverageCosineSimilairty: 0.916779
VectorExtremaCosineSimilarity: 0.709532
GreedyMatchingScore: 0.815786

after adding a period to each sentence in Hypothesis, results changed too:
> Bleu_1: 0.598540
Bleu_2: 0.495179
Bleu_3: 0.417247
Bleu_4: 0.382287
METEOR: 0.278276
ROUGE_L: 0.555841
CIDEr: 0.959262
SkipThoughtsCosineSimilarity: 0.807326
EmbeddingAverageCosineSimilarity: 0.921865
EmbeddingAverageCosineSimilairty: 0.921865
VectorExtremaCosineSimilarity: 0.675074
GreedyMatchingScore: 0.782153

These questions are important since metrics show the qualities of generated sentences. 

Thanks in advance.

**Comment by juharris** [comment]
It could be because of the way that we aggregate scores. Are any of the comments in #84 helpful?

**Comment by soloist97** [comment]
Thanks for your reply!

I found that the difference is caused by case and marks. After I  delete all the marks ('.' and ',')  and turn all letters to lowercase in Hypothesis and References. nlg-eval and coco-eval shared almost  the same results:

> Bleu_1: 0.631793
Bleu_2: 0.508748
Bleu_3: 0.424835
Bleu_4: 0.387489
METEOR: 0.274573
ROUGE_L: 0.555841
CIDEr: 1.053381
SkipThoughtsCosineSimilarity: 0.627871
EmbeddingAverageCosineSimilarity: 0.924776
EmbeddingAverageCosineSimilairty: 0.924776
VectorExtremaCosineSimilarity: 0.659306
GreedyMatchingScore: 0.791972

Maybe add an explanation in the project README.md to help others better utilize your work?

**Comment by juharris** [comment]
So coco-eval is sensitive to case and marks? I know this is somewhat of a standard to normalize for you but in general it's better not to do things without making it clear to the user. We can make a note but in general for a tool that should be mostly language agnostic, it would be weird to explicitly say that we do not do something.

**Comment by soloist97** [comment]
coco-eval is not sensitive to case and marks according to my toy experiments. 

I totally agree with your opinion. It's better to leave it to users themselves.

**Comment by juharris** [comment]
Sorry right that's what I meant.
